### ISSUE TITLE
Pass parameter to an extended object

### ISSUE THREAD

**Issue by skol-pro** [asleepinglion/superjs-base#1]
What is the best / easier way to pass parameters and get them as arguments in extend function ?

``` javascript
var Person = Class.extend({
    init: function() {
        // want to get lastname and apply it to this
    }
}):
var jack = new Person({lastname: 'Smith'});
```

Thank you so much !

**Comment by asleepinglion** [comment]
The init method acts as the constructor for the class. So you could do something like:

``` js
var Person = Class.extend({
    init: function(person) {
        console.log(person.lastname);
    }
}):
var jack = new Person({lastname: 'Smith'});
```

**Comment by asleepinglion** [comment]
I've updated the readme.md to include an explanation. Let me know if there is anything else. Happy coding!

**Comment by skol-pro** [comment]
Thank you very much for the time allowed !
To be more accurate on my issue, it was related to multiple extends.

``` javascript
init: function () {
    this._super(arguments);
}
```

This way I get arguments across multiple extends.

Thank you again !

**Comment by asleepinglion** [comment]
Yes that works if you wanted a dynamic amount of arguments to be passed down. You may wish to be more explicit and do something like:

``` js
var Person = Class.extend({
    init: function(person) {
        this._super(person);
    }
}):
var jack = new Person({lastname: 'Smith'});
```
